name: Build Rust Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-linux-android

    # CACHE UNTUK CARGO & BINARY
    - name: Cache Cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install cargo-apk
      run: |
        if ! command -v cargo-apk &> /dev/null; then
          cargo install cargo-apk
        else
          echo "cargo-apk already installed from cache"
        fi

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK
      run: |
        sdkmanager "ndk;26.1.10909125"
        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.1.10909125" >> $GITHUB_ENV

    - name: Build APK (Release Mode)
      run: cargo apk build --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: rust-native-app-release
        path: target/release/apk/*.apk
